Гюльзар -up-|> Гафар_Умеров
Сабре -up-|> Гафар_Умеров

Саид_Гафар_Оглы_Умеров -up-|> Гафар_Умеров
    Вера_Николаевна_Перетягина -right-> Саид_Гафар_Оглы_Умеров



Умаров_Адиль_Саидович -up-|> Саид_Гафар_Оглы_Умеров
    Вощинская_Нина_Александровна -right-> Умаров_Адиль_Саидович
Эльмира_Яхья_Заде_Саидовна -up-|> Саид_Гафар_Оглы_Умеров


Умарова_Наталья_Адильевна -up-|> Умаров_Адиль_Саидович
Пичугин_Юрий_Константинович -left-> Умарова_Наталья_Адильевна

Пичугин_Никита_Юрьевич -up-|> Умарова_Наталья_Адильевна
Пичугин_Павел_Юрьевич -up-|> Умарова_Наталья_Адильевна