class Гафар_Умеров{
    (возможно Умяров Кафар) жил в алупке или алуште в кипричном 
    2-х этажном доме на набережной
    учился в спб на факультете 
    естественных наук до революции
    - конец 19 века
    пережил Массовый террор в Крыму (1917—1918) и
    Красный террор в Крыму
    дружил с художником Николаем Ге (который был в крыму)
    умер при пересылке в казахстан после 2 мировой войны

    в крыму родился в богатой семье, алушта, любил женщин

    у Кафара было 3 дома и басеин(и пруд) и индюшка, маленький Саид ездил на индюшке.
    они были виноделами и торговцами.

    Вероятно, один из этих человек:
    https://ru.openlist.wiki/%D0%A3%D0%BC%D0%B5%D1%80%D0%BE%D0%B2_%D0%93%D0%B0%D1%84%D0%B0%D1%80_(1863)
    https://ru.openlist.wiki/%D0%A3%D0%BC%D0%B5%D1%80%D0%BE%D0%B2_%D0%90%D0%B1%D0%B4%D1%83%D0%BB%D0%B0_%D0%93%D0%B0%D1%84%D0%B0%D1%80_(1877)
    
    Возможно, его брат:
    https://ru.openlist.wiki/%D0%A3%D0%BC%D0%B5%D1%80%D0%BE%D0%B2_%D0%9C%D0%B0%D0%BC%D1%83%D1%82_%D0%93%D0%B0%D1%84%D0%B0%D1%80%D0%BE%D0%B2%D0%B8%D1%87_(1892)
}

Саид_Гафар_Оглы_Умеров -up-|> Гафар_Умеров
class Саид_Гафар_Оглы_Умеров{
    (возможно Сеит Ахмед Умер)
    сестра жила в ташкенте, ее вывезли из крыма в ташкент
    Гюльзар(не было детей) и Сабре(двое детей),
    дед Саид боялся татар
    и не оказывал им гостеприимтсва (сёстрам). жили сначала в подвале,
    потом дали квартиру на 3 семьи
    Саид хотел поплыть на корыте, и его за это хотели отдубасить
    не любил врачей и балет
    Умел жарить чебурки, и любил готовить. 
    Приезжал в Коломну к Адилю Саидовичу и они вместе ходили в лес за грибами
    Дед саид приехал в баку учиться в политехничеком институте
    жил в семинарии при мечете, в санатории познакомился с верой,
}


Вера_Николаевна_Перетягина -left-> Саид_Гафар_Оглы_Умеров
class Вера_Николаевна_Перетягина{

}

Умаров_Адиль_Саидович -up-|> Саид_Гафар_Оглы_Умеров
class Умаров_Адиль_Саидович{
Закончил школу в Баку и уехал учиться в ленинградский политехнический инстут
}

Эльмира_Яхья_Заде_Саидовна -up-|> Саид_Гафар_Оглы_Умеров
class Эльмира_Яхья_Заде_Саидовна{

}