class Кафар_Умяров_Умеров{
    жил в алупке или алуште в кипричном 2-х
    этажном доме на набережной
    учился в спб на факультете 
    естественных наук до революции
    - конец 19 века
    пережил Массовый террор в Крыму (1917—1918) и
    Красный террор в Крыму
    дружил с художником николаем ге (был в крыму)
    умер при пересылке в казахстан после 2 мировой войны

    в крыму родился в богатой семье, алушта, любил женщин

    у кафара было 3 дома и индюшка, саид ездил на индюшке,
    и басеин(и пруд). они делали вино
    они были торговцы
}

Саид_Кафар_Оглы_Умяров -up-|> Кафар_Умяров
class Саид_Кафар_Оглы_Умяров{
    сестра жила в ташкенте, ее вывезли из крыма в ташкент
    гюльзар(не было детей) и сабре(двое детей),
    дед саид боялся татар
    и не оказывал им гостеприимтсва. жили сначала в подвале,
    потом дали квартиру на 3 семьи
    саид хотел поплыть на корыте, и его за это хотели отдубасить
    не любил врачей и балет
}

Дедушка закончил школу и уехал в ленинградский политехнический инстут


Вера_Николаевна_Перетягина -left-> Саид_Кафар_Оглы_Умяров
class Вера_Николаевна_Перетягина{

}

Эля дочь саида, 
Дед саид приехал в баку учиться в политехничеком институте
жил в семинарии при мечете, в санатории познакомился с верой,